Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$DataDir=Join-Path $Root 'data';$StateFile=Join-Path $DataDir 'accounts_state.json';$ReceiptsDir=Join-Path $DataDir 'receipts';$Module=Join-Path $Root 'AccountState.ps1'
if(-not(Test-Path $Module)){[Windows.Forms.MessageBox]::Show('AccountState.ps1 not found.','Domlight','OK','Error')|Out-Null;exit 1}
. $Module
function Ensure-State{$items=@(Read-DomlightAccountState -Path $StateFile);if($items.Count -eq 0){$items=@(Get-DomlightArchiveAccounts -ReceiptsDir $ReceiptsDir);if($items.Count -gt 0){Write-DomlightAccountState -Path $StateFile -Items $items}};return @($items)}
function Status-Text($x){if([bool]$x.Excluded){return 'Исключен'};switch([string]$x.Status){'active'{'Активен'}'missing'{'Временно отсутствует'}'inactive'{'Неактивен'}default{[string]$x.Status}}}
$form=New-Object Windows.Forms.Form;$form.Text='Лицевые счета';$form.StartPosition='CenterScreen';$form.Size=New-Object Drawing.Size(1380,520);$form.MinimumSize=New-Object Drawing.Size(720,350);$form.Font=New-Object Drawing.Font('Segoe UI',10);$form.FormBorderStyle='Sizable';$form.MaximizeBox=$true
$label=New-Object Windows.Forms.Label;$label.Text='Исчезновение с портала не удаляет ЛС: 1-2 пропуска = временно отсутствует, 3+ = неактивен. Полное исключение выполняется только вручную.';$label.Location=New-Object Drawing.Point(20,15);$label.Size=New-Object Drawing.Size(1320,45);$label.Anchor='Top,Left,Right';$form.Controls.Add($label)
$grid=New-Object Windows.Forms.DataGridView;$grid.Location=New-Object Drawing.Point(20,65);$grid.Size=New-Object Drawing.Size(1320,300);$grid.ReadOnly=$true;$grid.AllowUserToAddRows=$false;$grid.SelectionMode='FullRowSelect';$grid.MultiSelect=$false;$grid.AutoGenerateColumns=$false;$grid.RowHeadersVisible=$false;$grid.AutoSizeRowsMode='AllCells';$grid.ScrollBars='Both';$grid.Anchor='Top,Bottom,Left,Right';$form.Controls.Add($grid)
foreach($spec in @(@('Account','Лицевой счёт',150),@('Address','Адрес',650),@('StatusText','Статус',195),@('MissingSuccessCount','Пропуски',90),@('LastSeenAt','Последняя проверка',170))){$c=New-Object Windows.Forms.DataGridViewTextBoxColumn;$c.Name=$spec[0];$c.DataPropertyName=$spec[0];$c.HeaderText=$spec[1];$c.Width=[int]$spec[2];if($spec[0]-eq 'Address'){$c.AutoSizeMode='Fill';$c.MinimumWidth=520;$c.DefaultCellStyle.WrapMode='True'}else{$c.AutoSizeMode='None'};[void]$grid.Columns.Add($c)}
$show=New-Object Windows.Forms.CheckBox;$show.Text='Показать исключенные';$show.Location=New-Object Drawing.Point(20,375);$show.Size=New-Object Drawing.Size(230,24);$show.Anchor='Bottom,Left';$form.Controls.Add($show)
function Refresh-Grid{$rows=New-Object System.Collections.ArrayList;foreach($x in @(Ensure-State)){if([bool]$x.Excluded -and -not $show.Checked){continue};$m=0;try{$m=[int]$x.MissingSuccessCount}catch{};[void]$rows.Add([pscustomobject]@{Account=[string]$x.Account;Address=$(if(-not [string]::IsNullOrWhiteSpace([string]$x.Address)){[string]$x.Address}elseif(-not [string]::IsNullOrWhiteSpace([string]$x.Apartment)){'кв. '+[string]$x.Apartment}else{'—'});StatusText=(Status-Text $x);MissingSuccessCount=$m;LastSeenAt=[string]$x.LastSeenAt})};$grid.DataSource=$null;$grid.DataSource=$rows}
$exclude=New-Object Windows.Forms.Button;$exclude.Text='Исключить из Domlight';$exclude.Location=New-Object Drawing.Point(270,405);$exclude.Size=New-Object Drawing.Size(220,42);$form.Controls.Add($exclude);$exclude.Anchor='Bottom,Left'
$restore=New-Object Windows.Forms.Button;$restore.Text='Восстановить';$restore.Location=New-Object Drawing.Point(500,405);$restore.Size=New-Object Drawing.Size(180,42);$form.Controls.Add($restore);$restore.Anchor='Bottom,Left'
$close=New-Object Windows.Forms.Button;$close.Text='Закрыть';$close.Location=New-Object Drawing.Point(690,405);$close.Size=New-Object Drawing.Size(180,42);$form.Controls.Add($close);$close.Anchor='Bottom,Left'
$show.Add_CheckedChanged({Refresh-Grid})
$exclude.Add_Click({try{if($grid.SelectedRows.Count-eq 0){return};$a=[string]$grid.SelectedRows[0].Cells['Account'].Value;$items=@(Ensure-State);$i=@($items|Where-Object{[string]$_.Account-eq$a})|Select-Object -First 1;if($null-eq$i-or[bool]$i.Excluded){return};$msg="ЛС $a будет постоянно исключён из Domlight.`r`n`r`nУдалить также локальные квитанции этого ЛС?`r`nДа — исключить и удалить архив`r`nНет — исключить, но оставить архив`r`nОтмена — ничего не менять";$c=[Windows.Forms.MessageBox]::Show($msg,'Исключить из Domlight',[Windows.Forms.MessageBoxButtons]::YesNoCancel,[Windows.Forms.MessageBoxIcon]::Warning);if($c-eq[Windows.Forms.DialogResult]::Cancel){return};$items=@(Set-DomlightAccountExcluded -Items $items -Account $a -Excluded $true);Write-DomlightAccountState -Path $StateFile -Items $items;if($c-eq[Windows.Forms.DialogResult]::Yes){foreach($f in @(Get-ChildItem -LiteralPath $ReceiptsDir -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name-match('^'+[regex]::Escape($a)+'(?:\s+-|$)')})){Remove-Item -LiteralPath $f.FullName -Recurse -Force -ErrorAction Stop}};Refresh-Grid}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message,'Domlight','OK','Error')|Out-Null}})
$restore.Add_Click({try{if($grid.SelectedRows.Count-eq 0){return};$a=[string]$grid.SelectedRows[0].Cells['Account'].Value;$items=@(Ensure-State);$i=@($items|Where-Object{[string]$_.Account-eq$a})|Select-Object -First 1;if($null-eq$i-or-not[bool]$i.Excluded){[Windows.Forms.MessageBox]::Show('Выберите исключённый лицевой счёт.','Domlight','OK','Information')|Out-Null;return};$items=@(Set-DomlightAccountExcluded -Items $items -Account $a -Excluded $false);Write-DomlightAccountState -Path $StateFile -Items $items;Refresh-Grid}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message,'Domlight','OK','Error')|Out-Null}})
$close.Add_Click({$form.Close()})
Refresh-Grid;[void]$form.ShowDialog()
